Repository DeveloperAcademy-POSTECH/MC3-Team14-FindAnimalFriends, pull requests merged in 2022-07, with the labels that each got.

#5 Feature/configure main vc
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/Contents.json
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/dolphinMemo.imageset/Contents.json
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/dolphinMemo.imageset/Image.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/elephantMemo.imageset/Contents.json
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/elephantMemo.imageset/Image.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/pandaMemo.imageset/Contents.json
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/pandaMemo.imageset/Image.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/polarbearMemo.imageset/Contents.json
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/polarbearMemo.imageset/Image.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/tigerMemo.imageset/Contents.json
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AnimalMemo/tigerMemo.imageset/Image.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/mainBackground.imageset/Contents.json
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/mainBackground.imageset/background.png
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/MainViewController.swift
Labels: enhancement

#36 Feature/configure light - Light(조명) mask 구성
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends/ClearTestViewController.swift
  FindAnimalFriends/FindAnimalFriends/EntranceView.swift
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/MainViewController.swift
  FindAnimalFriends/FindAnimalFriends/Memo.swift
Labels: enhancement

#44 Feat/onboarding sound
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/LaunchScreenController.swift
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/OnboardingSound/findAnimalFreidnsSound.wav
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/OnboardingSound/gameStartSound.wav
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/OnboardingSound/textSound.wav
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/OnboardingSound/textSound2.wav
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/OnboardingSound/textSound4.wav
  FindAnimalFriends/FindAnimalFriends/SceneDelegate.swift
Labels: enhancement

#45 [Feat] #39 thread를 고려해서 LaunchScreen 수정
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends/AppDelegate.swift
  FindAnimalFriends/FindAnimalFriends/SceneDelegate.swift
Labels: enhancement

#52 [Feat] Feature/entrance view branch merge
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends/ClearTestViewController.swift
  FindAnimalFriends/FindAnimalFriends/EntranceView.swift
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/MainViewController.swift
  FindAnimalFriends/FindAnimalFriends/Model/Data.swift
  FindAnimalFriends/FindAnimalFriends/ReadyView.swift
Labels: enhancement

#54 [Feat] codeReview 관한 수정
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/LaunchScreenController.swift
  FindAnimalFriends/FindAnimalFriends/SceneDelegate.swift
Labels: enhancement

#57 [Chore] 퀴즈 데이터 순서 변경, animalDict 순서 변경
  FindAnimalFriends/FindAnimalFriends/Model/AnimalQuizzes.json
  FindAnimalFriends/FindAnimalFriends/Model/DataModel.swift
Labels: documentation, enhancement

#61 [Feat] Connect data MainVC to QuizPageVC
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/QuizViewController.swift
Labels: enhancement

#64 [Feat] MainVC Animation debugging
  FindAnimalFriends/FindAnimalFriends/View/ReadyView.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
Labels: bug

#65 [Chore] AnimalQuizzes 문체 수정 및 퀴즈 수정.
  FindAnimalFriends/FindAnimalFriends/Model/AnimalQuizzes.json
Labels: documentation, enhancement, question

#67 [Feat] Mask Layer 로직 새로 구성
  FindAnimalFriends/FindAnimalFriends/View/ReadyView.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/QuizViewController.swift
Labels: bug, enhancement

#70 [Chore] animal quizzes 퀴즈 강조
  FindAnimalFriends/FindAnimalFriends/Model/AnimalQuizzes.json
Labels: documentation, enhancement

#72 Feat/sound관련작업
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/LaunchScreenController.swift
  FindAnimalFriends/FindAnimalFriends/Sound/pageFlipSound.wav
  FindAnimalFriends/FindAnimalFriends/Sound/startGameSound.wav
  FindAnimalFriends/FindAnimalFriends/Sound/textSound.wav
  FindAnimalFriends/FindAnimalFriends/Sound/textSound2.wav
  FindAnimalFriends/FindAnimalFriends/Sound/textSound3.wav
  FindAnimalFriends/FindAnimalFriends/Sound/typingSound.wav
  FindAnimalFriends/FindAnimalFriends/Sound/typingSound2.wav
  FindAnimalFriends/FindAnimalFriends/View/EntranceView.swift
  FindAnimalFriends/FindAnimalFriends/View/ReadyView.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
Labels: enhancement

#74 [Feat] Lottie CheckmarkView를 MainVC의 각 Memo버튼에 적용
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/Lottie/checkmark.json
  FindAnimalFriends/FindAnimalFriends/Model/Memo.swift
  FindAnimalFriends/FindAnimalFriends/View/CheckmarkLottieView.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
Labels: enhancement

#79 [Add] QuizExplanationView
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FindAnimalFriends/FindAnimalFriends/View/QuizExplanationView.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/QuizExplanationViewController.swift
Labels: enhancement

#80 [Feat] Feature/retry logic - 문제 다시 풀기 로직
  FindAnimalFriends/FindAnimalFriends/View/EntranceView.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/QuizViewController.swift
Labels: enhancement

#83 [Feat] MainVC sound
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/LaunchScreenController.swift
  FindAnimalFriends/FindAnimalFriends/View/EntranceView.swift
  FindAnimalFriends/FindAnimalFriends/View/ReadyView.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/QuizPageViewController.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/QuizViewController.swift
Labels: enhancement

#84 [Fix] quizExplanationView Data Connection
  FindAnimalFriends/FindAnimalFriends/View/QuizExplanationView.swift
Labels: bug

#85 [Fix] 사용되지 않는 quizExplanationViewController를 삭제해서 오류를 해결했습니다.
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends/ViewController/QuizExplanationViewController.swift
Labels: bug

#89 [Chore, Feat]/AnimalQuizzes doc, QuizExplanation
  FindAnimalFriends/FindAnimalFriends/Model/AnimalQuizzes.json
  FindAnimalFriends/FindAnimalFriends/View/QuizExplanationView.swift
Labels: documentation, enhancement

#94 [Add] #92 AppiconImage & LaunchImage추가
  FindAnimalFriends/FindAnimalFriends.xcodeproj/project.pbxproj
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/1024.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/114.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/120.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/180.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/29.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/40.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/57.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/58.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/60.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/80.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/87.png
  FindAnimalFriends/FindAnimalFriends/Assets.xcassets/AppIcon.appiconset/Contents.json
  FindAnimalFriends/FindAnimalFriends/Base.lproj/LaunchScreen.storyboard
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/LaunchImage/launchScreen.jpeg
Labels: enhancement

#96 [Bug] Zoom Animation 오류 수정 및 그 외 수정사항
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/LaunchScreenController.swift
  FindAnimalFriends/FindAnimalFriends/View/EntranceView.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
Labels: bug, enhancement

#98 [Fix] #92 launchScreen Location, lottieUserInteraction 수정
  FindAnimalFriends/FindAnimalFriends/Base.lproj/LaunchScreen.storyboard
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
Labels: enhancement

#103 [Feat] #102 Main VC에서 OnboardingVC 전환시 SplashView가 안뜨도록 수정
  FindAnimalFriends/FindAnimalFriends/Extension.swift
  FindAnimalFriends/FindAnimalFriends/LaunchScreen/LaunchScreenController.swift
  FindAnimalFriends/FindAnimalFriends/ViewController/MainViewController.swift
Labels: enhancement
